### ISSUE TITLE
DataGrid should allow more configurations for mobile render.

### ISSUE THREAD

**Issue by Serk352** [unosquare/tubular-react#453]
Currently, the DataGrid component doesn't allow to set a specific body renderer for mobile render, would be a good idea to set an extra prop for this, maybe called bodyRendererForMobile. I also think it would be a  good idea to expose the outerWidth value as a prop, to allow the user to set a specif resolution which determinates the use of the mobile render.

**Comment by geoperez** [comment]
I like the idea!

**Comment by kadosh** [comment]
Ideally we should be able to replace renderers with simple components. There's no valid reason we have at this moment to rely on renderers (maybe it was a design issue).

It would be nice to have the ability to override tubular-react components with your own ones.

1. Define default react components for normal and mobile body: TbRow and TbMobileRow. Please note that at this moment, the bodyRenderer is actually a rowRenderer, so we should just replace current "bodyRenderer" with TbRow default tubular component (to be created).

2. We should provide the ability to implement custom TbRow and TbMobileRow. So that, if any of those are defined, they should be used, instead of the default ones.

So, in the end we should have something like this:
```tsx
<DataGrid
  ...
  columns={columns}
  dataSource={data}
  rowComponent={customRowComponent}
  rowMobileComponent={customRowMobileComponent}
/>
```

Please let me know if you have any doubts or comments.

**Comment by Serk352** [comment]
@geoperez 
EOD Status:

I added two new components called it TbRow and TbMobileRow.
I refactored the DataGrid component to allow 3 new props.

These new props are: 
 mobileBreakpointWidth
 rowComponent 
 rowMobileComponent.

Estimated remaining time: 16 hours.

@kadosh the branch I'm using for work on these changes is **issue453-CustomComponentsForDataGrid**.

**Comment by geoperez** [comment]
Please update the documentation!

**Comment by geoperez** [comment]
Are you going to change anything else?

**Comment by Serk352** [comment]
@kadosh   @geoperez can we close this issue?
