### ISSUE TITLE
ColumnModel - not a class but an interface

### ISSUE THREAD

**Issue by neo7337** [unosquare/tubular-react#707]
**Describe the bug**
Hi Team, I am trying to use the tubular-react and tubular-common library but when I try to import the ColumnModel, it is being imported as an interface and not class

**To Reproduce**
https://codesandbox.io/s/818mwv72ll
You can visit this sandbox and can see that it has been imported as a class but when I try to do the same, it's been imported as an interface

**Expected behavior**
It should have been a class so that I can create my columns

**Comment by atjeff** [comment]
@neo7337 it has been changed to createColumn, use createColumn to create coulmns of type ColumnModel

**Comment by kadosh** [comment]
@neo7337 , as @atjeff mentioned, we have provided some helper functions to replace functionality we used to have on ColumnModel class.

The reason we changed ColumnModel into an interface was because the main reason for it to exist is to handle React state and since we need to deal with immutability it is better to work with simple props than doing it with classes.

In the end, you can simply create your columns with the helper functions.
