### ISSUE TITLE
ColumnModel is imported but never been used error

### ISSUE THREAD

**Issue by rohansrx** [unosquare/tubular-react#754]
while using new ColumnModel() it giving error that column model is not a constructor and also it is also giving import error that ColumnModel is imported but never been used error.
![image](https://user-images.githubusercontent.com/34603768/81478242-a22ef900-9239-11ea-97a8-44dd8bea1e2c.png)

**Comment by userpro100** [comment]
Sane issue happen with me.
Really need some help.
How to fix it??

**Comment by kadosh** [comment]
Hi @rohansrx , @userpro100 ,

We have been several changes in order to add more features to our grid. Our docs are out of date. But in order to fix that problem, you need to use createColumn from "tubular-common". It is a javascript function that will create your column model. The ColumnModel class was removed.

That should fix the issues you're facing.
