### ISSUE TITLE
In and After version 4.1.23 ColumnModel is not working and giving error

### ISSUE THREAD

**Issue by userpro100** [unosquare/tubular-react#755]
**Describe the bug**
In and After version 4.1.23 while import ColumnModel and implement it it gives a warning that column model is not a constructor also it also implies that column model is define but never used even after using it

**To Reproduce**
1. Go to codesandbox page of the tubular app
2. Click on dependencies
3. Change the version to latest

**Expected behavior**
Should able to define column

**Comment by kadosh** [comment]
We're sorry for the problems you're facing. We are working on updating our docs and codesandboxes.

Please use this link to see a working sample: https://codesandbox.io/s/tubular-react-template-gyjo8

The error you're seeing is because we have done major changes and we still need to upgrade codesandboxes.

**Comment by userpro100** [comment]
Hi,
The link you send me still has property error please check it again.
If you like i can help you with documentation.

**Comment by kadosh** [comment]
@userpro100, you're welcome to help on the docs. Please submit a PR and we will review it ASAP.

This is what I see on codesanbox:

![image](https://user-images.githubusercontent.com/399019/81568214-12856980-9363-11ea-84c9-c1b3e989893c.png)

**Comment by rohansrx** [comment]
Hi i have update the doc and create a PR but i still need some info on aggregate if available share some docs about aggregate function and filter type so we can make documentation better

**Comment by kadosh** [comment]
Hi @rohansrx, thanks for contributing to this project:

For aggregate, we have the following functions: None, Sum, Average, Count, DistinctCount, Max, Min. Each of them must be supported for Local and Remote data sources. So, whenever you have specified an aggregate function for a column, you should be able to get the result in the grid.

Check https://github.com/unosquare/tubular-react/blob/master/sample/src/CustomLayoutDataGrid.tsx

There you will see a custom footer component, who receives aggregates as a parameter. That aggregates.CustomerName is created because the CustomerName column definition is:

```tsx
   createColumn('CustomerName', {
        aggregate: AggregateFunctions.Count,
        filterable: true,
        searchable: true,
        sortable: true,
    }),
```

On filters, I don't know if it would be a good idea to work on the docs. You see, I have a milestone to implement major changes on them. You can check it at https://github.com/unosquare/tubular-react/issues/738. I think we can revisit filters docs after those major changes.

**Comment by rohansrx** [comment]
Ok thanks for reply
I will look after these and uodate the docs further.

It's a great project from your side that helps lot of people so thanks
